package:
  name: gps-timemachine
  version: "1.1.4"

source:
  path: ../

build:
  noarch: python
  script: |
    pytest && \
    python setup.py install

requirements:
  build:
    - python ~=3.10
    - pytest
  run:
    - python ~=3.10

test:
  imports:
    - gps_timemachine.gps

about:
  home: https://bitbucket.org/nsidc/gps-timemachine
  license: MIT
  summary: Adjust GPS datetimes to UTC.
