package:
  name: gps-timemachine
  version: "0.2.5"

source:
  path: ../

build:
  number: {{ environ.get('BUILD_NUMBER', 0) }}
  script: |
    mkdir -p reports/nose && \
    nosetests --verbose --with-xunit --xunit-file=reports/nose/xunit.xml && \
    python setup.py install

requirements:
  build:
    - flake8 3.3.0
    - flake8-quotes 0.9.0
    - nose 1.3.7
    - python
  run:
    - python

test:
 imports:
   - gps_timemachine.gps

about:
  home: https://bitbucket.org/nsidc/gps-timemachine
  license: MIT
  summary: Adjust GPS datetimes to UTC.
