name: gps-timemachine
channels:
- 'conda-forge'
- 'nodefaults'
dependencies:
  # package requirements
  - python ~=3.10
  # dev tools
  - bump2version
  - flake8
  - flake8-quotes
  - pytest
  - conda-lock
  # Build utilities
  - conda-build ~=24.5.1
  - boa ~=0.17.0
  - anaconda-client ~=1.12.3
