name: gps-timemachine
channels:
- 'conda-forge'
- 'defaults'
dependencies:
- conda-forge::bumpversion=0.5.3
- conda-forge::flake8=3.5
- conda-forge::flake8-quotes=0.12
- conda-forge::nose=1.3
- conda-forge::python=3.7
