version: 2
jobs:
  build:
    working_directory: ~/gps-timemachine
    docker:
      - image: continuumio/miniconda3:4.3.27
    steps:
      - checkout
      - run:
          name: Configure Conda
          command: .circleci/configure_conda.sh
      - run:
          name: Build Package
          command: |
            conda build recipe --python-version 3.5 && \
            conda build recipe --python-version 3.6 && \
            conda build recipe --python-version 3.7
      - store_artifacts:        # Only needed if you want to get them from the circleci interface
          path: /opt/conda/conda-bld/linux-64/
          destination: ~/gps-timemachine/artifacts
      - persist_to_workspace:
          root: /opt
          paths:
            - conda/conda-bld


  publish-to-main:
    working_directory: ~/gps-timemachine
    docker:
      - image: continuumio/miniconda3:4.3.27
    steps:
      - checkout
      - attach_workspace:
          at: /opt
      - run:
          name: Configure Conda
          command: .circleci/configure_conda.sh
      - run:
          name: publish to anaconda.org main channel
          command: |
            for ARTIFACT in $(ls ~/gps-timemachine/artifacts/*.tar.bz2) ; do
                for OS in 'linux-64', 'osx-64', 'win-32', 'win-64' ; do
                    conda convert ${ARTIFACT} -p ${OS} -o ~/gps-timemachine/artifacts
                    anaconda -t ${ANACONDA_TOKEN} upload -u nsidc ${ARTIFACT} -l main
                done
            done


workflows:
  version: 2
  build-all-and-deploy-releases:
    jobs:
      - build:
          filters:
            tags:
               only: /.*/

      - publish-to-main:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          context: org-global
