version: 2
jobs:
  build:
    working_directory: ~/gps-timemachine
    docker:
      - image: continuumio/miniconda3:4.6.14
    steps:
      - checkout
      - run:
          name: Configure Conda
          command: .circleci/configure_conda.sh
      - run:
          name: Build Package
          command: conda build recipe
      - persist_to_workspace:
          root: /opt
          paths:
            - conda/conda-bld


  publish-to-main:
    working_directory: ~/gps-timemachine
    docker:
      - image: continuumio/miniconda3:4.6.14
    steps:
      - checkout
      - attach_workspace:
          at: /opt
      - run:
          name: Configure Conda
          command: .circleci/configure_conda.sh
      - run:
          name: publish to anaconda.org main channel
          command: |
            ARTIFACT=`conda build . --output`
            anaconda -t ${ANACONDA_TOKEN} upload -u nsidc -l main ${ARTIFACT}


workflows:
  version: 2
  build-all-and-deploy-releases:
    jobs:
      - build:
          filters:
            tags:
               only: /.*/

      - publish-to-main:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          context: org-global
